language: node_js
node_js:
  - "0.11"
install:
  - npm install
script:
  - node --harmony-generators ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly --recursive -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
